"""empty message

Revision ID: 7713e940a751
Revises: 8d5ede3a1350
Create Date: 2023-04-14 17:26:47.366346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7713e940a751'
down_revision = '8d5ede3a1350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
